 #spring:
 #   datasource:
 #       driverClassName: com.mysql.jdbc.Driver
 #       url: jdbc:mysql://localhost:3306/beebook
 #       username: root
 #       password: A&Rics4u
 #   jpa:
 #       hibernate.ddl-auto: update
 #       generate-ddl: true
 #       show-sql: true